# OPTIONS RELATED TO LINE WIDTH ------------------
# First, options that `use_small_heuristics` affects
#fn_call_width = 60
#attr_fn_like_width = 70
#struct_lit_width = 70 # also see struct_lit_single_line 
#array_width = 60
#chain_width = 60
#single_line_if_else_max_width = 50

max_width = 80
use_small_heuristics = "Max"
enum_discrim_align_threshold = 80
struct_variant_width = 70 # is this affected by use_small_heuristics?
comment_width = 0


# STABLE OPTIONS ---------------------------------
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"

#disable_all_formating = false # use `ignore` instead

edition = "2021"
fn_args_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = false # does it work when they are separated by newline? Also see `group_imports`
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true


# UNSTABLE OPTIONS ------------------------------
color = "Auto"
combine_control_expr = true
condense_wildcard_suffixes = true

#control_brace_style = "AlwaysSameLine" # sometimes condition is really long

empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = false # what are the rules
format_strings = true
hex_literal_case = "Upper"
hide_parse_errors = false
ignore = []

#imports_indent = "Block" # i'd like to just have separate `use foo` for each line

imports_layout = "HorizontalVertical"

indent_style = "Block" # what is the difference for control flow?

inline_attribute_width = 0
license_template_path = ""
match_arm_block = true
imports_granularity = "Module"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
#required_version
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false # maybe on more complex expressions
struct_field_align_threshold = 60
struct_lit_single_line = true # what exactly means small?
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
version = "Two"
where_single_line = false
wrap_comments = true
